### ISSUE TITLE
Cannot find module ../../utils/config

### ISSUE THREAD

**Issue by jackdh** [ElectronHacked/nextjs-typescript-antd#2]
Running on Windows 10

```
...>yo nextjs-typescript-antd
module.js:549
    throw err;
    ^

Error: Cannot find module '../../utils/config'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\...\AppData\Roaming\npm\node_modules\generator-nextjs-typescript-antd\generators\app\index.js:3:24)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

C:\Users\...\Documents\...\...>
```

**Comment by fmaul** [comment]
I have the same error with node v12.6.0, yo@3.1.0 and  generator-nextjs-typescript-antd@2.0.1-alpha on MacOS
